/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Laboratory.glb --shadows --transform
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

export function Lab(props) {
  const { nodes } = useGLTF('/model/Laboratory-transformed.glb')
  return (
    <group {...props} dispose={null} name='laboratory'>
      <RigidBody colliders='trimesh' type='fixed' friction={0.05}>
        <group name='Scene'>
          <mesh castShadow receiveShadow geometry={nodes.Cube003.geometry}>
            <meshStandardMaterial attach="material" color='whitesmoke' />
          </mesh>
          <mesh castShadow receiveShadow geometry={nodes.Cube003_1.geometry}>
            <meshStandardMaterial attach="material" color='whitesmoke' />
          </mesh>
        </group>
      </RigidBody>
    </group>
  )
}

useGLTF.preload('/model/Laboratory-transformed.glb')
