/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Leo.glb --transform --shadows --keepnames
*/

import React, { useEffect, useRef, useState } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useXR } from '@react-three/xr';
import { Quaternion, Vector3 } from 'three';
import { BallCollider, RigidBody } from '@react-three/rapier';

const DIRECTION = new Vector3();
const ROTATION = new Quaternion();
const OFFSET = new Vector3();

export function LeoVR(props) {
  const group = useRef();
  const leoRef = useRef();
  const { nodes, materials, animations } = useGLTF('/Leo-transformed.glb');
  const { actions } = useAnimations(animations, group);

  // XR
  const { session, player } = useXR();

  // CONTROLLER

  // STATE
  const [pose, setPose] = useState('Idle');

  // EFFECT
  useEffect(() => { // Effect animation
    actions[pose].reset().fadeIn(0.3).play();

    return () => {
      actions[pose].fadeOut();
    }
  }, [pose]);

  // FRAME
  useFrame((state, delta, xrFrame) => {
    const leoLinvel = leoRef.current.linvel();
    const leoPosition = leoRef.current.translation();
    const leoRotation = leoRef.current.rotation();
    const cameraRotate = state.camera.matrix;
    
    const offset = OFFSET.set(0, 1.7, 1.5);
    offset.add(leoPosition);

    if (session) {
      const [xAxes, yAxes] = session.inputSources[1].gamepad.axes.slice(2,);

      DIRECTION.set(xAxes, 0, yAxes);
      leoRef.current.setLinvel({ x: DIRECTION.x, y: leoLinvel.y, z: DIRECTION.z });
      ROTATION.setFromRotationMatrix(cameraRotate);

      player.position.copy(offset);
      leoRef.current.setRotation({x: leoRotation.x, y: ROTATION.y, z: leoRotation.z, w: ROTATION.w});
    }
  });

  return (
    <RigidBody ref={leoRef} colliders={false} type='dynamic' position={[0, 2, 0]} lockRotations>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="Armature" rotation={[-Math.PI / 2, -Math.PI, 0]} scale={0.01}>
            <primitive object={nodes.mixamorig9Hips} />
            <skinnedMesh name="Ch31_Body" geometry={nodes.Ch31_Body.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Body.skeleton} />
            <skinnedMesh name="Ch31_Collar" geometry={nodes.Ch31_Collar.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Collar.skeleton} />
            <skinnedMesh name="Ch31_Eyelashes" geometry={nodes.Ch31_Eyelashes.geometry} material={materials.Ch31_hair} skeleton={nodes.Ch31_Eyelashes.skeleton} />
            <skinnedMesh name="Ch31_Hair" geometry={nodes.Ch31_Hair.geometry} material={materials.Ch31_hair} skeleton={nodes.Ch31_Hair.skeleton} />
            <skinnedMesh name="Ch31_Pants" geometry={nodes.Ch31_Pants.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Pants.skeleton} />
            <skinnedMesh name="Ch31_Shoes" geometry={nodes.Ch31_Shoes.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Shoes.skeleton} />
            <skinnedMesh name="Ch31_Sweater" geometry={nodes.Ch31_Sweater.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Sweater.skeleton} />
          </group>
        </group>
      </group>
      <BallCollider args={[0.3]} mass={10} position={[0, 0.3, 0]} />
    </RigidBody>
  );
}

useGLTF.preload('/Leo-transformed.glb');
