/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Leo.glb --transform --shadows --keepnames
*/

import React, { useRef, useState, useEffect } from 'react';
import { useGLTF, useAnimations, useKeyboardControls } from '@react-three/drei';
import { BallCollider, RigidBody } from '@react-three/rapier';
import { useFrame } from '@react-three/fiber';
import { Quaternion, Vector3 } from 'three';

const DIRECTION = new Vector3();
const lookDirection = new Quaternion();

export function Leonard(props) {
  const group = useRef();
  const leoRef = useRef();
  const { nodes, materials, animations } = useGLTF('/Leo-transformed.glb');
  const { actions } = useAnimations(animations, group);

  const [subKey, getKey] = useKeyboardControls();

  // STATE
  const [pose, setPose] = useState('Idle');

  // EFFECT
  useEffect(() => { // Effect animation
    actions[pose].reset().fadeIn(0.3).play();

    return () => {
      actions[pose].fadeOut();
    }
  }, [pose]);
  useEffect(() => { // Subscribe key
    return subKey(
      (state) => state,
    );
  }, []);

  // FRAME
  useFrame((state, delta) => {
    // const OFFSET = new Vector3(0, 1.7, -0.3);
    const pressingKey = getKey();
    const currentVelocity = leoRef.current.linvel();
    const currentRotation = leoRef.current.rotation();
    // const currentPosition = leoRef.current.translation();
    const cameraDirection = state.camera.quaternion;

    // OFFSET.applyQuaternion(currentRotation);
    // OFFSET.add(currentPosition);
    lookDirection.set(currentRotation.x, cameraDirection.y, currentRotation.z, cameraDirection.w);
    DIRECTION.set(pressingKey.right - pressingKey.left, 0, pressingKey.back - pressingKey.forward)
    .applyQuaternion(lookDirection);

    // state.camera.position.copy(OFFSET);
    leoRef.current.setRotation(lookDirection);
    leoRef.current.setLinvel({x: DIRECTION.x, y: currentVelocity.y, z: DIRECTION.z});
  });

  return (
    <RigidBody ref={leoRef} colliders={false} type='dynamic' position={[0, 2, 0]} lockRotations friction={0.01}>
      <group ref={group} {...props} dispose={null}>
        <group name="Scene">
          <group name="Armature" rotation={[-Math.PI / 2, Math.PI, 0]} scale={0.01}>
            <primitive object={nodes.mixamorig9Hips} />
            <skinnedMesh castShadow name="Ch31_Body" geometry={nodes.Ch31_Body.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Body.skeleton} />
            <skinnedMesh name="Ch31_Collar" geometry={nodes.Ch31_Collar.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Collar.skeleton} />
            <skinnedMesh name="Ch31_Eyelashes" geometry={nodes.Ch31_Eyelashes.geometry} material={materials.Ch31_hair} skeleton={nodes.Ch31_Eyelashes.skeleton} />
            <skinnedMesh name="Ch31_Hair" geometry={nodes.Ch31_Hair.geometry} material={materials.Ch31_hair} skeleton={nodes.Ch31_Hair.skeleton} />
            <skinnedMesh name="Ch31_Pants" geometry={nodes.Ch31_Pants.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Pants.skeleton} />
            <skinnedMesh name="Ch31_Shoes" geometry={nodes.Ch31_Shoes.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Shoes.skeleton} />
            <skinnedMesh name="Ch31_Sweater" geometry={nodes.Ch31_Sweater.geometry} material={materials.Ch31_body} skeleton={nodes.Ch31_Sweater.skeleton} />
          </group>
        </group>
      </group>
      <BallCollider args={[0.3]} mass={10} position={[0, 0.3, -0.08]} />
    </RigidBody>
  );
}

useGLTF.preload('/Leo-transformed.glb');
