/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 scene.gltf --shadows --transform
Author: Shedmon (https://sketchfab.com/shedmon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wooden-table-a95c3b0e61aa411a9e51ba2a2faee6fe
Title: Wooden table
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { RigidBody } from '@react-three/rapier'

const mejaPosition = [
  {
    x: [-8, -6, -4, -2, 2, 4, 6, 8],
    z: -4,
  },
  {
    x: [-8, -6, -4, -2, 2, 4, 6, 8],
    z: -2,
  },
  {
    x: [-8, -6, -4, -2, 2, 4, 6, 8],
    z: -0,
  },
  {
    x: [-8, -6, -4, -2, 2, 4, 6, 8],
    z: 2,
  },
];

export function Table(props) {
  const { nodes, materials } = useGLTF('/model/table-transformed.glb');

  return (
    <group {...props} dispose={null}>
      {
        mejaPosition.map((meja, index) => (
          meja.x.map((x, index) => {
            return (
              <RigidBody key={index} colliders='cuboid' type='fixed' position={[x-0.6, 0.26, meja.z]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Table} scale={0.25} />
              </RigidBody>
            );
          })
        ))
      }
    </group>
  )
}

useGLTF.preload('/model/table-transformed.glb')
